version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=fvchars
      - DB_PASSWORD=password
      - DB_NAME=fvchars

  db:
    image: postgres
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fvchars
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fvchars

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    hostname: frontend
    volumes:
      - ./frontend:/app

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
